from google import genai
from dotenv import load_dotenv
from pathlib import Path
from image_analyzer import analyze_image
import os
import pandas as pd
load_dotenv(Path(__file__).parent.parent / ".env")

client = genai.Client(
    api_key=os.getenv("GEMINI_API_KEY")
)



df = pd.read_csv("../dataset/claims.csv")

results = []

for _, row in df.iterrows():

    vision = analyze_claim_images(
        client,
        row["image_paths"],
        row["claim_object"]
    )

    status = decide(
        vision["issue_type"],
        vision["risk_flags"],
        vision["evidence_standard_met"]
    )

    results.append({
        "user_id": row["user_id"],
        "image_paths": row["image_paths"],
        "user_claim": row["user_claim"],
        "claim_object": row["claim_object"],

        "evidence_standard_met":
            vision["evidence_standard_met"],

        "evidence_standard_met_reason":
            vision["evidence_standard_met_reason"],

        "risk_flags":
            ";".join(vision["risk_flags"]),

        "issue_type":
            vision["issue_type"],

        "object_part":
            vision["object_part"],

        "claim_status":
            status,

        "claim_status_justification":
            "Generated by vision analysis",

        "supporting_image_ids":
            ";".join(
                vision["supporting_image_ids"]
            ),

        "valid_image":
            vision["valid_image"],

        "severity":
            vision["severity"]
    })